version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: always

  order_service:
    build: ./
    container_name: order_service
    environment:
      - NODE_ENV=production
      - LOG_ENV=production
      - PORT=8080
      - DB_HOSTNAME=mysql
      - MAP_KEY=AIzaSyBz_qEtbveatUdOjFgEBAqLWh2nvSrbe-4
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - ./:/opt/app/
    restart: always

volumes:
  mysql:
    driver: local
